version: '3.8'

services:
  backend:
    build:
      context: .
    ports:
      - "8080:8080"
    command: npm run dev
    environment:
      - MONGO_URL=${MONGO_URL}
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"

volumes:
  mongo-data: